
if (PyErr_Occurred())
{
	PyObject * type, * ERROR, * traceback;
	PyErr_Fetch(&type, &ERROR, &traceback);

	printf("Uh oh!\n");
	// NOTE(pebaz): Use this to view error: PyErr_Print();
	PyErr_Print();
	PyErr_Clear();
	//PyErr_SetString(PyExc_NameError, "Craft Error!\n");
	//return 0;

	// Create a Python Result object to return
    PyObject * ARGS_result = PyTuple_New(2);
    PyTuple_SET_ITEM(ARGS_result, 0, Py_BuildValue("s", "Craft Error!"));
	PyTuple_SET_ITEM(ARGS_result, 1, Py_True);
    PyObject * RET_result = PyObject_Call(get_result, ARGS_result, NULL);

	printf("here\n");
	if (RET_result != NULL)
	{
		// Check and see if it's a return/break/etc. exception or normal error
		// ...

		if (PyObject_SetAttrString(RET_result, "err", ERROR) != 0)
		{
			PyErr_Print();
			PyErr_Clear();
			RET_result = Py_None;
		}
		PyGILState_Release(gstate);
		return RET_result;
	}
	
	else {
		PyErr_Print();
		PyGILState_Release(gstate);
		return Py_None;
	}
	
} else {
	//printf("All good\n");
}
